- hosts: all
  vars:
#    condition_redhat: "ansible_facts['os_family'] == 'RedHat' and ansible_facts['memfree_mb'] >= 100" 
#    condition_ubuntu: "ansible_facts['os_family'] == 'Debian' and ansible_facts['memfree_mb'] >= 100"  
    Redhat: "httpd"
    Ubuntu: "apache2"
    Rservice: "httpd"
    Uservice: "apache2"
    Rstate: started
    Ustate: started
    package_state: present
    path: "/var/www/html/harsh.html"
  
  gather_facts: True

  tasks:
  - name: "Installing httpd in redhat"
    package:
      name: "{{Redhat}}"
      state: "{{package_state}}"
    register: output
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['memfree_mb'] >= 100 
    ignore_errors: True
    no_log: True
      
  - name: "Installing apache in Ubuntu"
    package:
      name: "{{Ubuntu}}"
      state: "{{package_state}}"
    register: result
    when: ansible_facts['os_family'] == 'Debian' and ansible_facts['memfree_mb'] >= 100 
    ignore_errors: True
    no_log: True

  - name: "Inside Redhat"
    debug:
      var:  output
  - name: "Inside ubuntu"
    debug:
      var: result


  - name: "Configuring Redhat webserver" 
    copy:
#     src: "/root/index.html"
      dest: "{{path}}"
      content: "hey there, welcome to redhat"
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['memfree_mb'] >= 100
    ignore_errors: True
    no_log: True

  - name: "Configuring Ubuntu webserver"
    copy:
#     src: "/root/index.html"
      dest: "{{path}}"
      content: "hey there, welcome to redhat"
    when: ansible_facts['os_family'] == 'Debian' and ansible_facts['memfree_mb'] >= 100
    ignore_errors: True
    no_log: True


  - name: "starting the web server in Rhel"
    service:
      name: "{{Rservice}}"
      state: "{{Rstate}}"
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['memfree_mb'] >= 100
    ignore_errors: True
    no_log: True


  - name: "starting the web server in Ubuntu"
    service:
      name: "{{Uservice}}"
      state: "{{Ustate}}"
    when: ansible_facts['os_family'] == 'Debian' and ansible_facts['memfree_mb'] >= 100
    ignore_errors: True
    no_log: True




      




